kind: LuaScript
apiVersion: api.ibm.com/v1
metadata:
  name: LuaScript-error-common
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  source: '-- error common'
