kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: telemetry-skt-common-seq
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  verbosity:
    - level: normal
      onSuccessTrimTo: basic
      operations:
        - method: GET
        - method: POST
        - method: PUT
        - method: DELETE
        - method: PATCH
        - method: HEAD
        - method: OPTIONS
