kind: Try
apiVersion: api.ibm.com/v1
metadata:
  name: Try-common-invoke
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  execute:
    - $ref: skt_common:LuaScript-set-common:1.0
    - $ref: skt_common:Invoke-common:1.0
  catch:
    - execute:
        - $ref: skt_common:LuaScript-catch-common:1.0
