kind: Authenticate
apiVersion: api.ibm.com/v1
metadata:
  name: Authenticate-apikey
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  operation:
    subscription: {}
