kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: Invoke-target
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        persistentConnections: false
        timeout: 30
        url: $(targetUrl)
        decompressResponse: false
        followRedirects: false
        chunkedUpload: false
  input: request
  output: response
