kind: LuaScript
apiVersion: api.ibm.com/v1
metadata:
  name: LuaScript-restore-orgreq
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  source: "-- orgin reqeust restore\r\nlocal res = context:get_message(\"res\")\r\n\r\nlocal req = context:create_message(\"req\", true)\r\n\r\nlocal originalReq = context:get_message(\"originalReq\")\r\n\r\n-- 응답 확인\r\nlocal auth = res.headers:get(\"Authorization\")\r\nlocal emergencyYn  = res.headers:get(\"emrgncy_sttconvs_yn\")\r\nlocal emergencyUrl = res.headers:get(\"emrgncy_routng_url\")\r\n\r\nif originalReq ~= nil then\r\n    -- Header & body 원복\r\n    req.headers = originalReq.headers\r\n    req.body:write(originalReq.body)\r\nend\r\n\r\n-- Nova token 설정\r\nif auth ~= nil then\r\n    req.headers:set(\"Authorization\", auth)\r\nend\r\n\r\n-- target url 비상전환 확인\r\nlocal targetHost = context:get(\"targetHost\")\r\nlocal path       = context:get(\"path\")\r\nlocal queryParam = context:get(\"queryParam\")\r\nlocal targetUrl\r\n\r\nif emergencyYn == \"Y\"\r\n    and emergencyUrl ~= nil\r\n    and emergencyUrl ~= \"\" then\r\n\r\n    targetUrl = emergencyUrl .. path .. queryParam\r\nelse\r\n    targetUrl = targetHost .. path .. queryParam\r\nend\r\n\r\ncontext:set(\"targetUrl\", targetUrl)\r\n\r\n"
