kind: LuaScript
apiVersion: api.ibm.com/v1
metadata:
  name: LuaScript-error-oauth
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  source: "-- error oauth\r\n\r\n-- oauth introspect failed\r\nerror('AIECO00009')"
