kind: LuaScript
apiVersion: api.ibm.com/v1
metadata:
  name: LuaScript-target-resp
  namespace: skt-commom
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  source: '-- backend Response change logic'
