kind: LuaScript
apiVersion: api.ibm.com/v1
metadata:
  name: LuaScript-set-orgreq
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  source: "-- original req\r\nlocal req = context:get_message(\"request\")\r\n\r\n-- 원본 Request 보관\r\nlocal originalReq = context:create_message(\"originalReq\", true)\r\n\r\noriginalReq.headers = req.headers\r\noriginalReq.body:write(req.body)"
