kind: Set
apiVersion: api.ibm.com/v1
metadata:
  name: Set-targetHost
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  valueType: plain
  variable:
    name: targetHost
    value: https://targethost.com
