kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: skt-common-api
  version: '1.0'
  namespace: skt_common
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./skt_common_api-spec.yml
  policy-sequence:
    - $ref: skt_common:skt-common-seq:1.0
