openapi: 3.0.4
info:
  title: skt_common_api
  version: '1.0'
  description: skt common api
paths:
  /:
    summary: ''
    description: ''
    get:
      responses: {}
servers:
  - url: /skt-common-api
