kind: Switch
apiVersion: api.ibm.com/v1
metadata:
  name: Switch-target
  namespace: skt-commom
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  cases:
    - condition: ($statusCode() = 200)
      execute:
        - $ref: skt_common:Return-common:1.0
  otherwise:
    - $ref: skt-commom:LuaScript-target-resp:1.0
