kind: Switch
apiVersion: api.ibm.com/v1
metadata:
  name: Switch-common
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  cases:
    - condition: ($statusCode() = 200)
      execute:
        - $ref: skt_common:LuaScript-restore-orgreq:1.0
        - $ref: skt_common:Try-common-res:1.0
  otherwise:
    - $ref: skt_common:Return-common:1.0
