kind: Throw
apiVersion: api.ibm.com/v1
metadata:
  name: Throw-erroroauth
  namespace: skt-commom
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  error:
    CustomError:
      message: AIECO00009
      messageType: plain
      status: 401
