kind: Throw
apiVersion: api.ibm.com/v1
metadata:
  name: Throw-3rdoauth
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  error:
    CustomError:
      message: AIECO00008
      messageType: plain
      status: 401
