kind: Try
apiVersion: api.ibm.com/v1
metadata:
  name: Try-apikey
  namespace: skt_common
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  execute:
    - $ref: skt_common:ExtractIdentity-apikey:1.0
    - $ref: skt_common:Authenticate-apikey:1.0
    - $ref: skt_common:Authorize-apikey:1.0
  catch:
    - execute:
        - $ref: skt_common:LuaScript-error_apikey:1.0
